---
reviewers:
  defaults:
    - default-reviewers

  groups:
    default-reviewers:
      - igaw
      - hreinecke
    ocp-reviewers:
      - arthurshau

  per_author:

files:
  '**':
    - default-reviewers
  'plugins/ocp/**':
    - ocp-reviewers

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
